import time
import json
import math
import random
import os
import sys
import threading
import pathway as pw

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import DEMO_SPIKE_PATH

from connectors.gemini_telemetry import (
    generate_telemetry_batch,
    init_vehicle_states,
    ROUTE_CORRIDORS,
    VEHICLES_BY_ROUTE,
    _interpolate_route,
    _check_spike,
)

# Re-export route and vehicle data for backward compatibility
ROUTES = ROUTE_CORRIDORS
VEHICLES = VEHICLES_BY_ROUTE


class TruckTelemetrySource(pw.io.python.ConnectorSubject):
    """Pathway custom connector using Gemini Flash for realistic truck telemetry.

    v2.0: Calls Gemini every 4th tick (8 seconds) for contextually-aware
    telemetry data. Physics-based interpolation for the other 3 ticks.
    Falls back entirely to physics if Gemini API unavailable.
    """

    def run(self) -> None:
        vehicle_states = init_vehicle_states()
        tick = 0

        # Initialize Gemini model
        model = None
        try:
            import google.generativeai as genai
            from dotenv import load_dotenv
            load_dotenv()
            genai.configure(api_key=os.environ.get("GEMINI_API_KEY", ""))
            model = genai.GenerativeModel("gemini-1.5-flash")
            print("[TruckTelemetry] Gemini Flash loaded — contextual telemetry active")
        except Exception as e:
            print(f"[TruckTelemetry] Gemini unavailable ({e}) — physics fallback only")

        while True:
            events = generate_telemetry_batch(vehicle_states, model, tick)
            ts = time.time()

            for event in events:
                vid = event["vehicle_id"]

                # Apply demo spike on top of Gemini/physics data
                if _check_spike(vid):
                    event["fuel_consumed_liters"] = round(
                        event["fuel_consumed_liters"] * 8.0, 3
                    )

                self.next_json({
                    "vehicle_id": vid,
                    "timestamp": ts,
                    "latitude": event["latitude"],
                    "longitude": event["longitude"],
                    "fuel_consumed_liters": round(event["fuel_consumed_liters"], 4),
                    "speed_kmph": round(event["speed_kmph"], 2),
                    "route_id": event["route_id"],
                    "load_status": event.get("load_status", "LADEN"),
                    "engine_temp_c": float(event.get("engine_temp_c", 91)),
                    "tyre_pressure_psi": float(event.get("tyre_pressure_psi", 38)),
                    "cargo_type": event.get("cargo_type", "General Freight"),
                    "weather": event.get("weather", "Clear"),
                })

            tick += 1
            time.sleep(2.0)


def build_telemetry_table() -> pw.Table:
    """Connect to the Gemini-powered telemetry source and return a typed Pathway table.

    v2.0 schema includes 5 new fields: load_status, engine_temp_c,
    tyre_pressure_psi, cargo_type, weather — all generated by Gemini.
    """
    return pw.io.python.read(
        TruckTelemetrySource(),
        schema=pw.schema_builder(
            columns={
                "vehicle_id": pw.column_definition(dtype=str),
                "timestamp": pw.column_definition(dtype=float),
                "latitude": pw.column_definition(dtype=float),
                "longitude": pw.column_definition(dtype=float),
                "fuel_consumed_liters": pw.column_definition(dtype=float),
                "speed_kmph": pw.column_definition(dtype=float),
                "route_id": pw.column_definition(dtype=str),
                "load_status": pw.column_definition(dtype=str),
                "engine_temp_c": pw.column_definition(dtype=float),
                "tyre_pressure_psi": pw.column_definition(dtype=float),
                "cargo_type": pw.column_definition(dtype=str),
                "weather": pw.column_definition(dtype=str),
            }
        ),
    )
